{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-environment-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  environment.yml: |-
{{ .Files.Get "config/environment.yaml" | nindent 4 }}
{{ end }}